# Generated by Django 3.1 on 2021-01-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210101_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draw',
            name='reel1',
            field=models.IntegerField(default=1552),
        ),
        migrations.AlterField(
            model_name='draw',
            name='reel2',
            field=models.IntegerField(default=1552),
        ),
        migrations.AlterField(
            model_name='draw',
            name='reel3',
            field=models.IntegerField(default=1552),
        ),
    ]
