# Generated by Django 3.1 on 2021-01-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210102_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='label',
            field=models.CharField(max_length=255),
        ),
    ]
